version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0902
      POSTGRES_DB: sqlfastdocker
    volumes:
      - ./data:/var/lib/postgresql/data